
dependencies:
- alias: oakary-ats-server
  name: oakary-ats-server
  version: 0.x.x
  repository: https://chartmuseum.jx.k8s.trunksys.com  
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- alias: preview
  name: react-app
  repository: file://../react-app
