apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    component: "slave"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name | quote }}
data:
  .env.production: |-
    PORT=4000
    REACT_APP_API_SERVER=http://{{ .Values.apiServiceName }}.{{ .Release.Namespace }}.k8s.trunksys.com/
    REACT_APP_API_ENDPOINT=http://{{ .Values.apiServiceName }}.{{ .Release.Namespace }}.k8s.trunksys.com/api
    REACT_APP_RECAPTCHA_KEY=[VUE_APP_RECAPTCHA_KEY]
