
dependencies:
- alias: api-server-name
  name: api-server-name
  version: 0.x.x
  repository: https://chartmuseum.jx.k8s.trunksys.com  
- alias: expose
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- alias: cleanup
  name: exposecontroller
  repository: https://chartmuseum.build.cd.jenkins-x.io
  version: 2.3.56
- alias: preview
  name: REPLACE_ME_APP_NAME
  repository: file://../react-app
